<?php 
require_once 'app/code/local/Expressly/Migrator/Helper/ExpresslyConfig.php';
$config = new ExpresslyConfig();
?>
<script>
	var baseUrl = "<?php echo Mage::getUrl(); ?>";
	var isRedirectEnabled = <?php echo $config->isRedirectEnabled(); ?>;
	var redirectDestination = "<?php echo $config->getRedirectDestination(); ?>";
	var isRedirectToLoginEnabled = <?php echo $config->isRedirectToLogin(); ?>;
</script>
