<script>
	var baseUrl = "<?php echo Mage::getUrl(); ?>";
	var authToken = "<?php echo Mage::registry('modulePass'); ?>";
	var tickIco = '<img src="<?php echo $this->getSkinUrl('images/tick.png') ?>" />';
	var crossIco = '<img src="<?php echo $this->getSkinUrl('images/cross.png') ?>" />';
</script>

<h1>Expressly Admin Panel</h1>
<img id="expresslyLogo" src="<?php echo $this->getSkinUrl('images/Logo_Blue_s.jpg') ?>" />
<div class="clearer"></div>
<br /><br />
<!-- General options tab -->
<div class="entry-edit">
    <div class="section-config">
        <div class="entry-edit-head collapseable">
            <a id="general_config-head" href="#" onclick="Fieldset.toggleCollapse('general_config', ''); return false;" class="">General config</a>
        </div>
        <input id="general_config-state" type="hidden" value="0" name="config_state[general_config]">
        <fieldset style="display: none;" class="config collapseable" id="general_config">
            <form method="post" action="<?php echo $this->getUrl('*/*/storeRedirectDestination'); ?>" onsubmit="return checkNewRedirectAddress();">
                <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                <input type="checkbox" name="redirect-users" onclick="updateRedirectEnabled(this)" <?php if(Mage::registry('redirectEnabled') == "true") { ?>checked="checked"<?php } ?> /> Redirect users? <?php echo str_replace("index.php/", "", Mage::getUrl()); ?><input type="text" id="redirect-destination-field" name="redirect-destination" value="<?php echo Mage::registry('redirectDestination'); ?>"  <?php if(Mage::registry('redirectEnabled') != "true") { ?>disabled="disabled"<?php } ?>/><a id="userRedirectionTestLink" href="JavaScript:testUserRedirection();" <?php if(Mage::registry('redirectEnabled') != "true") { ?>style="display:none"<?php } ?>>Test redirection</a>
            	<br />
                <input class="expresslyLargeButton" type="submit" name="save" value="Save" />
            </form>
            <br /><br />
            <input type="checkbox" name="post-checkout-box" onclick="updatePostCheckoutBox(this)" <?php if(Mage::registry('postCheckoutBox') == "true") { ?>checked="checked"<?php } ?> disabled="disabled" /> Include promo recommendation on order page
            <br />
            <input type="checkbox" name="redirect-to-login" onclick="updateRedirectToLogin(this)" <?php if(Mage::registry('redirectToLogin') == "true") { ?>checked="checked"<?php } ?> /> Redirect existing customers to login
        </fieldset>
    </div>
</div>

<!-- Endpoint check tab -->
<div class="entry-edit">
    <div class="section-config">
        <div class="entry-edit-head collapseable">
            <a id="endpoint_check-head" href="#" onclick="Fieldset.toggleCollapse('endpoint_check', ''); return false;" class="">Endpoint check</a>
        </div>
        <input id="endpoint_check-state" type="hidden" value="0" name="config_state[endpoint_check]">
        <fieldset style="display: none;" class="config collapseable" id="endpoint_check">
            <br />
            <a href="JavaScript:runEndpointTests()"><div id="endpointCheckLauncher">Launch endpoint check</div></a>
            <br /><br />
            <span class="underlineText">Self endpoints</span><br /><br />
            <div class="selfCheckStepName"><span class="modulecheckstepname" id="checkStep1">User&nbsp;creation</span></div><div class="selfCheckStepResult"><span class="modulechecstep_1_result"></span></div><div id="modulechecstep_1_howtofix"><span class="underlineText"><a href="JavaScript:void(0)" onclick="showHowToFixContent('modulechecstep_1_howtofix')">How to fix it</a></span><div class="howtofix_content">It is possible that the test user has been left in your system (or was previously present). Go to Customers -> Manage customers and find the user with endpoint.test@buyexpressly.com e-mail address, and delete it. If the problem is still occurs, please contact expressly.</div></div><br />
            <div class="selfCheckStepName"><span class="modulecheckstepname" id="checkStep2">User&nbsp;information</span></div><div class="selfCheckStepResult"><span class="modulechecstep_2_result"></span></div><div id="modulechecstep_2_howtofix"><span class="underlineText"><a href="JavaScript:void(0)" onclick="showHowToFixContent('modulechecstep_2_howtofix')">How to fix it</a></span><div class="howtofix_content">It is possible that the test user has been left in your system (or was previously present). Go to Customers -> Manage customers and find the user with endpoint.test@buyexpressly.com e-mail address, and delete it. If the problem is still occurs, please contact expressly.</div></div><br />
            <br /><br />
            <span class="underlineText">External endpoint</span><br /><br />
            <div class="selfCheckStepName"><span class="modulecheckstepname" id="checkStep5">Migration&nbsp;service&nbsp;availability</span></div><div class="selfCheckStepResult"><span class="modulechecstep_5_result"></span></div><div id="modulechecstep_5_howtofix"><span class="underlineText"><a href="JavaScript:void(0)" onclick="showHowToFixContent('modulechecstep_5_howtofix')">How to fix it</a></span><div class="howtofix_content">Please contact expressly</div></div><br />
            
            <div id="module_check_result"></div>
            <br />
        </fieldset>
    </div>
</div>

<!-- Campaign management tab -->
<div class="entry-edit">
    <div class="section-config">
        <div class="entry-edit-head collapseable">
            <a id="campaign_management-head" href="#" onclick="Fieldset.toggleCollapse('campaign_management', ''); return false;" class="">Campaign management</a>
        </div>
        <input id="campaign_management-state" type="hidden" value="0" name="config_state[campaign_management]">
        <fieldset style="display: none;" class="config collapseable" id="campaign_management">
            <i>Self management coming soon</i> - contact us at campaigns@buyexpressly.com to setup a campaign
        </fieldset>
    </div>
</div>

<!-- Security -->
<div class="entry-edit">
    <div class="section-config">
        <div class="entry-edit-head collapseable">
            <a id="security-head" href="#" onclick="Fieldset.toggleCollapse('security', ''); return false;" class="">Security</a>
        </div>
        <input id="security-state" type="hidden" value="0" name="config_state[security]">
        <fieldset style="display: none;" class="config collapseable" id="security">
            <span class="underlineText">Change module password</span>
            <br />
            (this will prevent Expressly to connect to your store, if the password is not communicated back)
            <br /><br />
            <form method="post" action="<?php echo $this->getUrl('*/*/storeModulePass'); ?>" onsubmit="return confirm('The new password will be sent to expressly')">
                <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                <input class="expresslyLongInput" type="text" name="modulePass" value="<?php echo htmlspecialchars(Mage::registry('pureModulePass')); ?>" />
                <br /><br />
                <input class="expresslyLargeButton" type="submit" name="save" value="Save" />
            </form>
        </fieldset>
    </div>
</div>